default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: sssss
  port: 5432

development:
  <<: *default
  database: notes_app_development
  
test:
  <<: *default
  database: notes_app_test
  
production:
  <<: *default
  database: notes_app_production
  username: notes_app
  password: <%= ENV["NOTES_APP_DATABASE_PASSWORD"] %>
